# Generated by Django 5.2.5 on 2025-09-25 14:52

import django.core.files.storage
import django.db.models.deletion
import the_messages.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brief_desc', models.CharField(max_length=72)),
                ('biography', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='/home/vickerdent/python_apps/vickerdentstudios/media'), upload_to='author_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(choices=[('Audio', 'audio'), ('Video', 'video')], default='audio', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('thumbnail', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='/home/vickerdent/python_apps/vickerdentstudios/media'), upload_to=the_messages.models.GenerateMessageThumbnailPath())),
                ('part_of_group', models.BooleanField(default=False)),
                ('session', models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Night', 'Night')], max_length=100, null=True)),
                ('is_sunday_service', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('message_length', models.CharField(max_length=7)),
                ('category', models.CharField(blank=True, max_length=75, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='the_messages.author')),
                ('media_types', models.ManyToManyField(related_name='messages', to='the_messages.mediatype')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='/home/vickerdent/python_apps/vickerdentstudios/media'), upload_to=the_messages.models.GenerateAttachmentPath())),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('media_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='the_messages.mediatype')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='the_messages.message')),
            ],
        ),
        migrations.CreateModel(
            name='MessageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='/home/vickerdent/python_apps/vickerdentstudios/media'), upload_to='group_thumbnails/')),
                ('is_conference', models.BooleanField(default=False)),
                ('conference_name', models.CharField(blank=True, max_length=255, null=True)),
                ('conference_tag', models.CharField(blank=True, max_length=30, null=True)),
                ('month', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('no_of_speakers', models.IntegerField(default=1)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('UC', 'Upcoming'), ('OG', 'Ongoing'), ('C', 'Completed')], default='UC', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_groups', to='the_messages.author')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='message_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='the_messages.messagegroup'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='the_messages.message')),
                ('session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='the_messages.session')),
            ],
        ),
    ]
