# Generated by Django 5.2.5 on 2025-09-26 10:43

import django_backblaze_b2.storage
import the_messages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(max_length=255, storage=django_backblaze_b2.storage.BackblazeB2Storage(), upload_to=the_messages.models.GenerateAttachmentPath()),
        ),
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=django_backblaze_b2.storage.BackblazeB2Storage(), upload_to='author_photos/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=django_backblaze_b2.storage.BackblazeB2Storage(), upload_to=the_messages.models.GenerateMessageThumbnailPath()),
        ),
        migrations.AlterField(
            model_name='messagegroup',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=django_backblaze_b2.storage.BackblazeB2Storage(), upload_to='group_thumbnails/'),
        ),
    ]
