# Generated by Django 5.2.6 on 2025-10-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediatype',
            name='type_name',
            field=models.CharField(choices=[('Audio', 'Audio'), ('Video', 'video')], default='Audio', max_length=10, unique=True),
        ),
    ]
