name: Deploy on server
on:
  push:
    branches:
      - production
jobs:
  deploy:
    name: Deploy branch production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and restart the server
        uses: appleboy/ssh-action@master
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          envs: SSH_AUTH_SOCK
          script: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
            ssh-add - <<< "${{ secrets.PRIVATE_KEY }}"
            cd /home/vickerdent/studios_app
            source venv/bin/activate
            git checkout production
            git pull
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            sudo systemctl restart nginx
            sudo systemctl restart gunicorn
