name: Deploy on server
on:
  push:
    branches:
      - prod
jobs:
  deploy:
    name: Deploy branch prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and restart the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            su vickerdent
            cd /home/vickerdent/studios_app
            source venv/bin/activate
            git config --global user.email "${{ secrets.GIT_EMAIL }}"
            git config --global user.name "${{ secrets.GIT_USERNAME }}"
            git checkout prod
            git pull
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            sudo systemctl restart nginx
            sudo systemctl restart gunicorn
