name: Deploy on server
on:
  push:
    branches:
      - prod
jobs:
  deploy:
    name: Deploy branch prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and restart the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: echo hello world here I come > hello.txt
